kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}-data
  labels:
    app.kubernetes.io/name: {{ .Values.database.name }}
    app.kubernetes.io/version: {{ .Values.database.image.tag | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize | quote }}
  volumeMode: Filesystem
