apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name }}
    app.kubernetes.io/version: {{ .Values.database.image.tag | quote }}
type: Opaque
stringData:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | quote }}
  {{ .Values.database.rootPasswordKey }}: {{ .Values.database.rootPassword | quote }}
