apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Values.database.name }}-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.database.name }}
      app.kubernetes.io/version: {{ .Values.database.image.tag | quote }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.database.port }}
