apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/version: {{ .Values.image.tag | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
        networking/allow-matomo-mysql: {{ .Values.matomoLabels.allowMysql | quote }}
        networking/allow-istio-ingress-8080: {{ .Values.matomoLabels.allowIstioIngress8080 | quote }}
        networking/allow-smtp-submission: {{ .Values.matomoLabels.allowSmtpSubmission | quote }}
        networking/allow-cloudfront-egress: {{ .Values.matomoLabels.allowCloudfrontEgress | quote }}
        networking/allow-cloudflare-egress: {{ .Values.matomoLabels.allowCloudflareEgress | quote }}
        networking/allow-softgarden-egress: {{ .Values.matomoLabels.allowSoftgardenEgress | quote }}
    spec:
      hostAliases:
        - ip: {{ .Values.hostAlias.ip | quote }}
          hostnames:
            - {{ .Values.hostAlias.hostname | quote }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.securityContext.seccompProfileType }}
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MATOMO_DATABASE_HOST
              value: {{ .Values.database.name | quote }}
            - name: MATOMO_DATABASE_ADAPTER
              value: {{ .Values.matomoDatabase.adapter }}
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: {{ .Values.matomoDatabase.tablePrefix | quote }}
            - name: MATOMO_DATABASE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}
            - name: MATOMO_DATABASE_DBNAME
              value: {{ .Values.database.database | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpTargetPort }}
            - name: https
              containerPort: {{ .Values.service.httpsTargetPort }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: matomo-data
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data
